### ISSUE TITLE
Unload Extension

### ISSUE THREAD

**Issue by GVX111** [ExtCore/ExtCore#10]
how to unload loaded extension?

**Comment by DmitrySikorsky** [comment]
Not possible in current version. Now I'm moving ExtCore to the new ASP.NET Core RC2, and because of everything is changed there now it is hard to say whether we will have this feature in ExtCore soon or not. Anyway, I'm going to add this ability in the future.

**Comment by GVX111** [comment]
if we can load assembly new domain maybe possible, in current appdomain can't unload. RC2 has ApplicationPart.

**Comment by DmitrySikorsky** [comment]
Yes, ApplicationParts is cool feature, now I'm exploring it.

**Comment by almasvas** [comment]
> Not possible in current version. Now I'm moving ExtCore to the new ASP.NET Core RC2, and because of everything is changed there now it is hard to say whether we will have this feature in ExtCore soon or not. Anyway, I'm going to add this ability in the future.

So. Did you add this ability?)

**Comment by DmitrySikorsky** [comment]
No, and it won't be possible. ExtCore is too complex for such feature, because there is no problem to unload an extension (I've made many tests, loaded assembly, created instance of a type from it, run code on it, unload the assembly, tried to create instance again with errror; it worked), but there are problems inside the ASP.NET itself, the way how it discovers controllers, routes etc. Once they are discovered you can't remove them. At least I haven't found a solution.
