### ISSUE TITLE
Cannot find  file or assembly

### ISSUE THREAD

**Issue by shayanblest** [ExtCore/ExtCore#100]
Hi 
I have an extension that uses the UAParser to parse the User Agent string to the client information.
But, When I Install UAParser Package from nuget gallery to Extension the error occurs.

> cannot find file or assembly...

but when I install the package to the main webApplication that fixes the error and it is not suitable for the extendable application because the extension developer does not have access to the main WebApplication Packages to add or remove them.

**Comment by DmitrySikorsky** [comment]
Hi! I think that is because your extension uses some package (has reference to it) which dll is not put to the extensions folder AND not referenced by the main web app. For example, if your package A has dependency to B, you must put both A.dll and B.dll to the extensions folder (or your main web app must have dependency to B). Otherwise A.dll won't be able to be loaded (and it is logically correct).

**Comment by shayanblest** [comment]
Thanks a lot ... 
You are very great
