### ISSUE TITLE
Area issue

### ISSUE THREAD

**Issue by canperk** [ExtCore/ExtCore#130]
We have 5 class libraries as module projects and then we are using each of theses modules as areas in our .Net Core project. When we add all cshtml files as embedded resource files, some how same named controllers and views are being overriden after publishing the project. 

For example: 
MainProject > Home > Index
Project1 > Home > Index
Project2 > Home > Index

After deployment, what ever if we wanna access /Home/Index it is opening Project2/Home/Index

We can not configure class libraries with area path

**Comment by DmitrySikorsky** [comment]
So, you can use the same view names in different areas for sure using the ExtCore, because MVC resolves views based on their areas, and ExtCore doesn't change this behavior anyhow.

Here is the sample:

https://github.com/Platformus/Platformus/blob/master/src/Platformus.Barebone.Backend/Areas/Backend/Controllers/DefaultController.cs#L10

https://github.com/Platformus/Platformus/blob/master/src/Platformus.Routing.Frontend/Controllers/DefaultController.cs#L11

Two controllers have the same name (one of them is in the area, another one is not), and they are resolved correctly.

**Comment by canperk** [comment]
During debugging your explanations are completely true and we are making it as you said. However when we published the application, things have changed.

**Comment by canperk** [comment]
We have solved this issue by removing Views folder from publish root folder. Basically adding lines that are written below, in csproj file can help for quick jobs

  <ItemGroup>
    <Content Remove="Views\**" />
    <Content Remove="wwwroot\**" />
  </ItemGroup>
