### ISSUE TITLE
Change all Netcoreapp projects to Netstandard!!

### ISSUE THREAD

**Issue by DanielS4n** [ExtCore/ExtCore#135]
To integrate with other netstandard libraries (like Blazor) it would be necessary to use netstandard2.0 instead of netcoreapp2.1, I changed all the references in the projects from netcoreapp2.0 to netstandard2.0, then in all .csproj:
     < TargetFramework > netcoreapp2.1 < / targetFramework >
TO:
     < TargetFramework> netstandard2.0 < / targetFramework >
ADDING THE RELATIVE NAMESPACE (same as AssemblyName):
     < RootNamespace > ExtCore .... < / RootNamespace >

  Then it is necessary to eliminate the following reference in the projects where present:
   < ItemGroup >
     < PackageReference Include = "Microsoft.AspNetCore.App" Version = "2.1.1" / >
   < / ItemGroup >

EXCEPTION OF: ExtCore.WebApplication
THAN IN Extcore.Infrastructure NEED REFERENCE TO: Microsoft.AspNetCore..

Therefore it is necessary to apply displacements / structural optimizations for the following sources:
IConfigureAction.cs
IConfigureServicesAction.cs

**Comment by DmitrySikorsky** [comment]
Yes, that will be done very soon, I have number of such requests, so I will do that ASAP.

As I remember, I have tried to do that (maybe with the previous version of .net standard). But when I did so, I couldn't built the app because .net standard didn't contain IServiceProvider, IApplicationBuilder and some other interfaces... Perhaps now it is changed. I need to check.

So can you run it on top of the full .NET? Not Core?
