### ISSUE TITLE
Multi-tenant application using ExtCore

### ISSUE THREAD

**Issue by ptawde95** [ExtCore/ExtCore#156]
Thinking of using ExtCore for multi-tenant web application. Will it be a best approach to begin with ??
please suggest..

**Comment by DmitrySikorsky** [comment]
Hi, ExtCore is low-level framework, it allows to build any kind of application. I use it in one project that support multitenancy and it works good.

**Comment by ptawde95** [comment]
Thanks for your quick response.

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. If you have any questions or need some help or examples feel free to reopen it any momeny.

**Comment by mkgn** [comment]
Sorry for re-opening this. But I thought this is the best place to ask the question since it's about multi-tenancy. ExtCore seems to embed views and static resources to the extension/module we build. So in a multi-tenant environment what if a tenant want to customize a file? Is it possible to do something like this;

BaseApp
  |
  Extentions
     Tenant1
        ExtentionA, ExtentionB, ....
     Tenant2
        ExtentionA, ExtentionB, ....

So, for tenant specific functionality we can use something like say SaaSkit, but the ExtCore will help in modularization of the system. Views/Css/jpg etc... will not be embeded to the assembly so that they can be customized for each tenant. I think this is simlar to OrchardCore.

Any input from your end?

**Comment by DmitrySikorsky** [comment]
It is not so difficult. Usually I just use some /AccountName/ folder level to store account-specific things like views, images etc. You can replace the view locator with your own, it is very easy, and it will work. And then you can have every account data in a separate assembly.
