### ISSUE TITLE
Plans and recommendation

### ISSUE THREAD

**Issue by Razgort** [ExtCore/ExtCore#164]
Hello guys,
I'm very interesting in your project.
In fact i'm building for my company a large application. 
This app is based on asp core and angular 7.
But we want this app to be extensible on the backend part AND on the front (angular) part.
Because we will publish this app compiled and give it to our integrators that will want to do their own specific development around our app. I'm not sure if i'm understandable.
Ask me if not.

But anyway in our study case would you recommand we use your framework ?
Also we will migrate to asp core 3.0 once it will be in release. Do you have plans for supporting it ?

Thanks in advance,
Alexandre MOULAY

**Comment by DmitrySikorsky** [comment]
Hi @Razgort, thank you for your question.

I think in your case it might be a good idea to use ExtCore, because it is tested in many applications and works well. It is really simple, and it doesn't do anything special, doesn't change the way things work normally, so it is really easy to add or remove ExtCore in the project.

When .NET Core 3 is released, I want to review the project, I think I will have to make changes to the assembly loading mechanism etc. But we in our company use it all the time, so I am positive that we will release the new versions and support it in the future.

I will be happy to have some ideas from you, what features you need etc.

**Comment by Razgort** [comment]
Hello,
Thanks for the answer !!
That's great news i will try to integrate it then.
Will it be difficult to migrate when you will review for .net core 3 ?
Do you have a working example with an angular or other SPA application working ?
Any advice on a solution to build an extensible angular SPA app inside the same project of the extcore main app ?

If i have some ideas or any thoughts i will whisper you then =)

**Comment by agtokty** [comment]
Hi all , this is what i am looking for.
As far as ı understand ExtCore frontend is based  on dotnet viewcomponents. Is there any architecture suggestion or best practices to apply my extension based dotnet-angular project.

**Comment by DmitrySikorsky** [comment]
@Razgort I don't have any good example of using ExtCore with Angular, but I think you just need to start thinking in a modular way :) Please, take a look at:

https://github.com/ExtCore/ExtCore-Sample-Modular-Ui-Adv
https://github.com/ExtCore/ExtCore-Sample-Modular-Ui

Your extensions might have parts of the Angular application inside their assemblies, or you can ship backend and frontend separated.

**Comment by DmitrySikorsky** [comment]
@agtokty thanks for the answer! ExtCore is more backend-oriented framework, so you can use anything on frontend. Please take a look at the links I've sent on the previous message.

**Comment by Razgort** [comment]
Hello guys,
@agtokty It is exactly what i am trying to build here , if you achieve to make a good sample i would love to check it if you please.

Thanks in advance

**Comment by Xarkam** [comment]
Hello,

I arrive a bit late in the conversation, but I think you must structure your project to compile the angular part before injecting the rendering of the compilation as embedded resources in the dll.

It is also possible to configure the application to not use embedded resources, but rather in a folder / wwwroot.

The problem here is the compilation of angularjs files before compiling and running the extcore project.

**Comment by DmitrySikorsky** [comment]
That would be amazing if somebody find some time to write small tutorial about ExtCore + Angular.

**Comment by Armarr** [comment]
We investigated using Angular with ExtCore for an internal project.
The main challenge is to load in modules at runtime because with Angular 2+ there is a compilation step involved. We ended up sticking to MVC with some trickery (Turbolinks) because of this hurdle though it does seem like others have gotten this to work. It seems like in React or Vue this is easier to do.
https://stackoverflow.com/questions/50149016/load-new-modules-dynamically-in-run-time-with-angular-cli-angular-5/50395048

**Comment by Xarkam** [comment]
Hello @Armarr 

I did a little bit of research and came across this: https://github.com/mithunvp/ngGitHouse/tree/master/ngGitHouse

Maybe that could help you.

**Comment by DmitrySikorsky** [comment]
So guys, ASP.NET Core 3 should be released on September as I know. I want to start thinking about ExtCore 5. I've just reviewed all the issues, closed some of them, and created new ones. I think the most important features are:

0. Moving to ASP.NET 3.
1. Assemblies loading/unloading at runtime. I've looked at some articles and it seems it should be possible now with the new ALC.
2. Embedded file provider always was a problem (you need to rebuild the project when some CSS or JS file in your extension project is changed and so on). I want to make it more flexible. #168.
3. Multiple storage context providers support. I have been asked many times about that, and I need this option even in my own projects, so it will be implemented.
4. Some smaller issues will be fixed too. See 5.0.0 milestone for details.

Please, share your ideas here, let's make our project better. Thanks!

**Comment by DmitrySikorsky** [comment]
Closing for now to keep things more clear.
