### ISSUE TITLE
roadmap and help needed

### ISSUE THREAD

**Issue by viktor-evdokimov** [ExtCore/ExtCore#3]
HI, I like what you guys started here. Do you have a roadmap or list of things you need help with?

**Comment by DmitrySikorsky** [comment]
Hi! Thanks for your interest in the project!

No, currently I don't have any roadmap and this is not good. But I want to create it in the discussion with users. If you have any ideas/comments I'll be very grateful if you share them here or in Gitter: https://gitter.im/ExtCore/ExtCore

What I'm doing right now is changing the way ExtCore stores found assemblies. Instead of having one ExtensionManager class I want to have container for the assemblies and another one class for getting implementations or instances of the given types, because this functions are duplicated in few places now and it is common use case.

Also now I have 4 large blocks to work with:

1. ExtCore itself.
2. ExtCore samples.
3. Docs (docs.extcore.net).
4. Website (extcore.net).

**Comment by ojosdegris** [comment]
Thanks, Dmitry
I think until new ideas come up let me play a bit with samples and improve docs out of it, as they are pretty empty now.

**Comment by MukundRayate** [comment]
Hi Dmitry,
        First of all you guys are having amazing idea , I appreciate your work. Even I am spent plenty of time to Google on such topic. I am very much interesting in this . I desperately waiting for walk-through and road map.

**Comment by DmitrySikorsky** [comment]
Thanks for your feedback, it is very important for me! I will publish walk-through and road map asap.

**Comment by DmitrySikorsky** [comment]
Created some basic roadmap: https://github.com/ExtCore/ExtCore/wiki/Roadmap.
I think we can organize ideas by versions. Current version in NuGet is alpha-5. New version here (and in Roadmap) is alpha-6.

**Comment by MukundRayate** [comment]
HI , I have one question regarding dependency , it will modify acceding to your setup of VS  , in this case extcore fire excetion. "Could not load file or assembly 'System.Reflection.TypeExtensions' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515) " . i think extcore and application has distinct dependency  . Have you face same condition ??

**Comment by DmitrySikorsky** [comment]
Hi! Yes, I have. If your extension A has dependency to some lib B you need to copy that lib B to the extensions folder too in order extension A to be loaded. OR you can add direct dependency to lib B to the project.json of your main web application. OR you can add direct dependency to extension A to the project.json of your main web application (but this is not applicable if you want to use extensions as dlls).

So this is known issue and currently I can't find any graceful solution for that.

**Comment by jvelezc** [comment]
good job so far. let me know if you need any task done. I can help out in my "spare time"

**Comment by DmitrySikorsky** [comment]
@jvelezc Thanks! For now (after the last update) it seems that ExtCore is ready for beta (after testing), because it fits all needs I can imagine for this moment. So I would be happy if you could help with some code review or ideas, what is done in wrong way, what features are missing etc. After that we can create issues for these fixes.

**Comment by brzezinol** [comment]
I will try to use your framework in may app.
Do you still working on this project?

**Comment by DmitrySikorsky** [comment]
Yes, I'm working on the project and I'm not going to stop. Now I think it is ready for 1.0.0 release, but I would like to move ASP.NET to 1.0.1 before. I'm focused on docs now: http://docs.extcore.net/en/latest/

You can also take a look at Platformus project as a huge sample: https://github.com/platformus/Platformus/

Feel free to ask if you have any questions. Here on in Gitter.
