### ISSUE TITLE
ExtCore and ASP.Net core MVC with default template

### ISSUE THREAD

**Issue by Brouilles** [ExtCore/ExtCore#31]
Hello,
I am very interested by ExtCore. I understand it is in develop and that the documentation is not complete. But I tried the built in an existing project ASP.net MVC Core 1.0.0, I'm no expert in ASP.net Core, I can not properly configure the Startup because in the documentation, "IHostingEnvironment env" is not present. My explanations may not be clear, but if you have a solution I'm interested, starting from the default MVC template.

I apologize for my bad English.
Thank you for your answers,
Best regards

**Comment by DmitrySikorsky** [comment]
Hi! I understand your question. You want to have the IHostingEnvironment env in your Startup.Configure method. You can get it like this:

    public override void Configure(IApplicationBuilder applicationBuilder)
    {
      IHostingEnvironment env = this.serviceProvider.GetService<IHostingEnvironment>();

      if (env.IsDevelopment())
      {
        applicationBuilder.UseDeveloperExceptionPage();
        applicationBuilder.UseDatabaseErrorPage();
        applicationBuilder.UseBrowserLink();
      }

      base.Configure(applicationBuilder);
    }

So just use this.serviceProvider.GetService to get any service instead of having it in the method parameters. It has the same result as:

    public override void Configure(IApplicationBuilder applicationBuilder, IHostingEnvironment env)
    {
      if (env.IsDevelopment())
      {
        applicationBuilder.UseDeveloperExceptionPage();
        applicationBuilder.UseDatabaseErrorPage();
        applicationBuilder.UseBrowserLink();
      }

      base.Configure(applicationBuilder);
    }

We are using this.serviceProvider.GetService because we can't change the method signature when overriding it.

**Comment by Brouilles** [comment]
Hi,
Thank you for your reply. Your project is very interesting and I wish you good luck. I'll follow him, too bad I do not have the skills to participate in development.

Just one question, do you recommend the use of a SQLite or SQL ?
Thank you,
Best regards

**Comment by DmitrySikorsky** [comment]
Thank you, it is very important for me to know, that the project is useful.

What about the SQLite or SQL server, I think it is good idea to start from SQLite because it is very easy (you don't need to setup anything), and then, if you have problems with performance, you could easily move to SQL Server. Also SQL Server provides much more features and there is Express, free version (I'm using it and like it very much), but for small apps it is a bit too much.
