### ISSUE TITLE
Option to temporary disabling Extension Loading in config.json

### ISSUE THREAD

**Issue by DavidNorena** [ExtCore/ExtCore#56]
Hi, I was playing around with your nice project, and I thought what if you wanna "disable" or "ignore" loading extensions even if they are referenced or inside your extensions folder ?

What if you wanna to disable a extension without "uninstalling" it, just modifying your config.json.

This will be usefull if you want to disable  that extension for a while, for maintenance, or something without deleting the reference or the file inside the extension folder.

I have a pull request with my aproximation ... but is my idea useful ?

Thanks and good work guys !

**Comment by DmitrySikorsky** [comment]
Hi! Thank you! Yes, I was thinking about that too. But if the application has implicit dependency on some package, it will load the assembly and controllers will be resolved from that assembly automatically. And I don't see any possibility to unload that assembly. We only may mark the assemblies like "turned off" inside the ExtensionManager, but it not used for the everything (it is used almost for everything). What do you think about this?

**Comment by DavidNorena** [comment]
Yeah i haven't seen a way to runtime unload extensions, but i'll keep looking for resources, wow I didnt see the implicit dependency from another package scenario... i need to think about it ... the only change I made was to ignore the extension discovering and loading in the assembly provider, reading the value of the "ignored" assemblies from the config.json

**Comment by DavidNorena** [comment]
I need to deep discover one extension dependencies (parent extension) to see if it contains the ignored extension name (child extension)... if true, parent extension will also be ignored right ?

**Comment by DmitrySikorsky** [comment]
I think this is difficult task. Let's see. We may have extension A that uses extension B, C and D. We have the dependency on A in our project. Also we may have some code that uses types from B, C and D, but that assemblies are not implicit referenced. We have them because A has corresponding references. So if we disable our assembly A from loading we will broke our application.

**Comment by DavidNorena** [comment]
yep I was thinking the same too, but for assemblies that are not referenced, maybe like a EmailSenderService or something will be a good idea

**Comment by DmitrySikorsky** [comment]
You know, I think it is very specific task. So it might be fixed be implementing custom IAssemblyProvider: http://docs.extcore.net/en/latest/fundamentals/default_assembly_provider.html

I don't think we should make it a part of the ExtCore, because it is too specific. It would be cool to add ability to load/unload assemblies at runtime and not only while the initialization. The first part seems to be possible while the second one (unloading) is not.

**Comment by DavidNorena** [comment]
Ok thanks for your time and clearing the subject, i'm closing the issue then, thanks man
