### ISSUE TITLE
Load extensions in defined order ?

### ISSUE THREAD

**Issue by Xarkam** [ExtCore/ExtCore#77]
Hello,

I look in documentation and examples, but I don't see if extcore have special feature for load extensions in defined order.

In platfortmus, I see domain is the entry point for the cms but how is determined the load sequence of extensions.

Example: load security before form or filemanager.

Thanks.

**Comment by DmitrySikorsky** [comment]
Hi! What is the reason to load dlls in a special order? You CAN execute actions in a special order, but why to load dlls? Is it important?

**Comment by Xarkam** [comment]
Hi!
For example, initializing database objects.
If I am not logged in, you can have access to the database to read the login information.

Unless you need to initialize the data access layers outside of an extension?

**Comment by DmitrySikorsky** [comment]
I think database access is not related to authentication and dll loading order. Your application restricts the access, so it (application itself) always has full access to the database, but it can control the access level for the users depending on their login status. I'm not sure I understand this question. Could you provide some sample or so?

**Comment by postb99** [comment]
Hi Dmitry,

I am Xarkam's wife. We discussed about what we want to understand the correct way of developing it.

You got the point, we are wondering about managing extensions "activation" as services. For example, a request is processed, the application uses the database access extension that checks (once) whether database works/has been created, then another extension manages login etc.

We tought of initializing database only at first use of application rather than at startup.

Another idea would be that several extensions can provide their own entities/db tables, so this should be called in right order.

In Platformus, I see "Actions" with Priority and implementation of IConfigureService. I think this allows to register services/execute some code in desired order? For platformus: Barebone (priority 1000) then Security (2000) then Globalization (3000).

Maybe can you point us to useful to read ASP.NET Core documentation?

**Comment by DmitrySikorsky** [comment]
Hi @postb99! Yes, you are right about Platformus actions and their order. I'm still a bit confused with your task, I'm not sure I fully understand it, but. So, every extension can execute its code inside the web application global ConfigureServices and Confugure method in a specific order (it is done with actions, they have priority and actions are sorted using priority before been executed). Also, for example ExtCore.Mvc extension runs such action to register ASP.NET Core MVC. And moreover, it adds another actions that other extensions can use to run their code inside MVC configuration methods. So your extension might declare some interface, then get all implementations of that interface and call method inside it (optionally using priority).

For example, [UseMvcAction](https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.Mvc/Actions/UseMvcAction.cs#L19) class is action that will be executed by the ExtCore inside the Configure method with priority 10000. So everything that have priority lower than 10000 will be executed first. So 10 will be executed before 1000 and 1000 before 10000.

As you can see, this action executes [another set of the actions](https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.Mvc/Actions/UseMvcAction.cs#L40). They might be used to register routes. They are executed using priority too.

**Comment by postb99** [comment]
Thanks for the explaination and the links, the question can be closed now.

**Comment by DmitrySikorsky** [comment]
@postb99 Good! Feel free to reopen it at any moment if you have any questions.
