### ISSUE TITLE
[Question] ext core extensions / EF core design

### ISSUE THREAD

**Issue by postb99** [ExtCore/ExtCore#82]
Hi Dmitry,

Sorry for asking here but I don't know how to do it else. I have a question regarding the extensions data layer. The designs tells that there is an abstraction project and a project for each implemented provider. Hovewer, since EF Core has some provider abstraction leveraging, what code should be put in the provider implementation project and what in the abstraction project (in an abstract class I guess)?

I typically looked into Platformus Security extension. After a quick look, most of the repositories implementation code is similar. The entity registration code too (IEntityRegistrar implementation). The only difference I clearly noticed was the definition of auto-incremented primary key.  You generally use "etb.Property(e => e.Id).ValueGeneratedOnAdd();", and for SqlServer you rather use "etb.Property(e => e.Id).UseSqlServerIdentityColumn();". I browsed the EF Core issues to find that UseSqlServerIdentityColumn() may be removed in future. I clearly don't know much about it, but guess ValueGeneratedOnAdd() works for every database provider. I will give a try to see the generated schema.

Learning before coding more on my own project :-) Best regards.

**Comment by DmitrySikorsky** [comment]
Yes, you are right, it is almost the same. But. There are some cases when I have to executed raw SQL statements to  (for example) delete a lot of related things when deleting main entry.  For example,  take a look at Platformus.Domain extension and ClassRepository's Delete method. And in that places I have to write different SQL for different databases. That's why I have separated implementations.

**Comment by DmitrySikorsky** [comment]
Please, feel free to reopen this issue if you still have any questions.
