### ISSUE TITLE
[Question] About database initialization

### ISSUE THREAD

**Issue by postb99** [ExtCore/ExtCore#88]
Hi Dmitry,

My app will check at startup if the database exists. I read that I could do that using EF Core in an ExtCore EFCore repository class with this code: "storageContext.Database.EnsureCreated();".

For now I'm still working on making this call work. But I rather call this in a module than in a repository.

I was wondering about adding some method to IStorageContext such as "EnsureDatabaseCreated()" or so. Indeed, ExtCore is ORM-agnostic, so, EF Core is a choice among another choices. In my case, with EF Core, I cast the IStorageContext to EF's StorageContextBase.

How do you handle this question in Platformus? Thanks for the ideas.

**Edit**
After reading some EF Core tutorials, everything isn't clear to me yet (I'm new to EF :) ):
- do I need to create my own DbContext as I see in the EF Core tutorials? Doesn't ExtCore EF create it already? In Startup I configure the storage context options but don't register the db context service. [Edit 2: answering to myself: DbContext is available whenever I have a IStorageContext reference].
- what code calls the RegisterEntities method? For now I set a low priority to my EnsureCreated method call so it gets called before RegisterEntities, I think it is wrong.
- I read some docs about migration and that you can call this programmatically.

I have the approach of creating the database from the application because I want the extensions to add their own tables (in addition to records).

**Comment by DmitrySikorsky** [comment]
Hi! Please take a look also at #72.

I don't use migrations or automatic db handling, I do everything related to storage manually (because it is quick and simple for me). But. A lot of people ask this questions about  migrations and db managing, so we really need these tasks to be solved.

I'm going to try to discover this and give some feedback.

What about storage context. ExtCore uses implementation of the IStorageContext that is registered inside the DI by ExtCore itself. But it is very easy to implement that interface (you can copy the implementation),  change it and register your one. In this case you can use Identity.

**Comment by postb99** [comment]
I close this issue because #89 will solve it I think.
