### ISSUE TITLE
[Question] About IStorageContext

### ISSUE THREAD

**Issue by postb99** [ExtCore/ExtCore#97]
Hi Dmitry,

After your changes in #96, I had to modify some of my own code [with additional cast here](https://github.com/SOFTINUX/Base/blob/840d39dd9951161641cef1f2de92814004437074/Security.Data.EntityFramework/PermissionRepository.cs#L32) and [many ugly casts :-) here](https://github.com/SOFTINUX/Base/blob/840d39dd9951161641cef1f2de92814004437074/Security.Data.EntityFramework/PermissionRepository.cs#L53)

Thus a question, why not adding `.Entry(T)` and `.Set<T>` to IStorageContext interface? These methods seem agnostic enough to be added to interface, although they come from Entity Framework first.

**Comment by DmitrySikorsky** [comment]
Yes, I've found this issue too today. I think, that was not so good idea and I should  fix it in beta3. The reason I did it is here: https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.Data.EntityFramework/RepositoryBase.cs#L25

When I had `protected IStorageContext storageContext;` defined as `StorageContextBase`, I had to cast `storageContext` to `StorageContextBase` in the `SetStorageContext` method in order to assign the value to the variable. That made impossible to assign any implementation of the `IStorageContext` interface, except ones that inherit `StorageContextBase`. So it was not possible to use Identity.

Now I don't know what to do. Whether I have to make `storageContext` member to have `StorageContextBase` type again, or to write some extension method that will return `IStorageContext` as `DbContext`. I think that we should have the member with `IStorageContext` as type, because it should be possible to assign any implementation of that interface. From other point of view, this `RepositoryBase` class is related to the `EntityFramework`, so maybe that variable should have `DbContext` type.

I don't think we should add some members to the `IStorageContext` interface, because they are related only to the EF. And there are more members that should be available, like transactions, Database property etc.

What do you think?

**Comment by DmitrySikorsky** [comment]
Perhaps, we should add some additional member to the EF implementation of the repository. Like,

`protected DbContext dbContext;`

So we will have both `storageContext` and `dbContext` members. But I don't like this idea.

**Comment by DmitrySikorsky** [comment]
...So, after some research,  I think the best way would be to modify `RepositoryBase<TEntity>` class like this:

  ```
public abstract class RepositoryBase<TEntity> : IRepository where TEntity : class, IEntity
  {
    protected DbContext storageContext;
    protected DbSet<TEntity> dbSet;

    public void SetStorageContext(IStorageContext storageContext)
    {
      this.storageContext = storageContext as DbContext;
      this.dbSet = this.storageContext.Set<TEntity>();
    }
  }

```

This seems to be logical to have EF DbContext object inside the EF repositories without any casts. And you still have to provide the implementation of the IStorageContext interface.

I'm going to fix this tomorrow if you don't have any comments regarding this.

**Comment by postb99** [comment]
Thanks for the research, it sounds very good like this, it is consistent !

**Comment by Xarkam** [comment]
Thank you. I will quickly update and remove all the cast that we had put.
